export const exampleflakes = [
  {
    _id: "1",
    name: "Cheerios",
    brand: "General Mills",
    ingredients: [
      "Whole Grain Oats",
      "Corn Starch",
      "Sugar",
      "Salt",
      "Tripotassium Phosphate",
      "Vitamin E",
    ],
    nutritional_table: [
      "Calories: 100",
      "Total Fat: 2g",
      "Cholesterol: 0mg",
      "Sodium: 140mg",
      "Total Carbohydrate: 20g",
      "Protein: 3g",
    ],
    image_url: "<https://example.com/cheerios.jpg>",
  },
  {
    _id: "2",
    name: "Frosted Flakes",
    brand: "Kellogg's",
    ingredients: [
      "Milled Corn",
      "Sugar",
      "Malt Flavoring",
      "High Fructose Corn Syrup",
      "Salt",
    ],
    nutritional_table: [
      "Calories: 110",
      "Total Fat: 0g",
      "Cholesterol: 0mg",
      "Sodium: 150mg",
      "Total Carbohydrate: 26g",
      "Protein: 1g",
    ],
    image_url: "<https://example.com/frosted-flakes.jpg>",
  },
  {
    _id: "3",
    name: "Lucky Charms",
    brand: "General Mills",
    ingredients: [
      "Whole Grain Oats",
      "Marshmallows",
      "Sugar",
      "Corn Syrup",
      "Modified Corn Starch",
    ],
    nutritional_table: [
      "Calories: 110",
      "Total Fat: 1.5g",
      "Cholesterol: 0mg",
      "Sodium: 170mg",
      "Total Carbohydrate: 23g",
      "Protein: 2g",
    ],
    image_url: "<https://example.com/lucky-charms.jpg>",
  },
  {
    _id: "4",
    name: "Raisin Bran",
    brand: "Kellogg's",
    ingredients: [
      "Whole Grain Wheat",
      "Raisins",
      "Wheat Bran",
      "Sugar",
      "Barley Malt Extract",
    ],
    nutritional_table: [
      "Calories: 190",
      "Total Fat: 1g",
      "Cholesterol: 0mg",
      "Sodium: 200mg",
      "Total Carbohydrate: 46g",
      "Protein: 4g",
    ],
    image_url: "<https://example.com/raisin-bran.jpg>",
  },
  {
    _id: "5",
    name: "Cocoa Puffs",
    brand: "General Mills",
    ingredients: [
      "Whole Grain Corn",
      "Sugar",
      "Corn Meal",
      "Corn Syrup",
      "Cocoa",
    ],
    nutritional_table: [
      "Calories: 110",
      "Total Fat: 1.5g",
      "Cholesterol: 0mg",
      "Sodium: 140mg",
      "Total Carbohydrate: 25g",
      "Protein: 1g",
    ],
    image_url: "<https://example.com/cocoa-puffs.jpg>",
  },
  {
    _id: "6",
    name: "Honey Nut Cheerios",
    brand: "General Mills",
    ingredients: [
      "Whole Grain Oats",
      "Sugar",
      "Oat Bran",
      "Corn Starch",
      "Honey",
    ],
    nutritional_table: [
      "Calories: 110",
      "Total Fat: 1.5g",
      "Cholesterol: 0mg",
      "Sodium: 190mg",
      "Total Carbohydrate: 23g",
      "Protein: 2g",
    ],
    image_url: "<https://example.com/honey-nut-cheerios.jpg>",
  },
  {
    _id: "7",
    name: "Frosted Mini-Wheats",
    brand: "Kellogg's",
    ingredients: ["Whole Grain Wheat", "Sugar", "Gelatin", "BHT"],
    nutritional_table: [
      "Calories: 190",
      "Total Fat: 1g",
      "Cholesterol: 0mg",
      "Sodium: 0mg",
      "Total Carbohydrate: 46g",
      "Protein: 5g",
    ],
    image_url: "<https://example.com/frosted-mini-wheats.jpg>",
  },
  {
    _id: "8",
    name: "Corn Flakes",
    brand: "Kellogg's",
    ingredients: ["Milled Corn", "Sugar", "Malt Flavoring", "Salt"],
    nutritional_table: [
      "Calories: 100",
      "Total Fat: 0g",
      "Cholesterol: 0mg",
      "Sodium: 200mg",
      "Total Carbohydrate: 24g",
      "Protein: 2g",
    ],
    image_url: "<https://example.com/corn-flakes.jpg>",
  },
  {
    _id: "9",
    name: "Special K",
    brand: "Kellogg's",
    ingredients: [
      "Rice",
      "Wheat Gluten",
      "Sugar",
      "Defatted Wheat Germ",
      "Salt",
    ],
    nutritional_table: [
      "Calories: 120",
      "Total Fat: 0g",
      "Cholesterol: 0mg",
      "Sodium: 220mg",
      "Total Carbohydrate: 22g",
      "Protein: 6g",
    ],
    image_url: "<https://example.com/special-k.jpg>",
  },
  {
    _id: "10",
    name: "Fruit Loops",
    brand: "Kellogg's",
    ingredients: ["Corn", "Wheat", "Sugar", "Oat Flour", "Salt"],
    nutritional_table: [
      "Calories: 110",
      "Total Fat: 1g",
      "Cholesterol: 0mg",
      "Sodium: 135mg",
      "Total Carbohydrate: 25g",
      "Protein: 1g",
    ],
    image_url: "<https://example.com/fruit-loops.jpg>",
  },
  {
    _id: "11",
    name: "Cocoa Pebbles",
    brand: "Post",
    ingredients: [
      "Rice",
      "Sugar",
      "Hydrogenated Vegetable Oil",
      "Cocoa",
      "Salt",
    ],
    nutritional_table: [
      "Calories: 110",
      "Total Fat: 1g",
      "Cholesterol: 0mg",
      "Sodium: 170mg",
      "Total Carbohydrate: 25g",
      "Protein: 1g",
    ],
    image_url: "<https://example.com/cocoa-pebbles.jpg>",
  },
  {
    _id: "12",
    name: "Cinnamon Toast Crunch",
    brand: "General Mills",
    ingredients: [
      "Whole Grain Wheat",
      "Sugar",
      "Rice Flour",
      "Canola Oil",
      "Cinnamon",
    ],
    nutritional_table: [
      "Calories: 130",
      "Total Fat: 3g",
      "Cholesterol: 0mg",
      "Sodium: 210mg",
      "Total Carbohydrate: 23g",
      "Protein: 1g",
    ],
    image_url: "<https://example.com/cinnamon-toast-crunch.jpg>",
  },
  {
    _id: "13",
    name: "Cap'n Crunch",
    brand: "Quaker",
    ingredients: ["Corn Flour", "Sugar", "Oat Flour", "Brown Sugar", "Salt"],
    nutritional_table: [
      "Calories: 120",
      "Total Fat: 1.5g",
      "Cholesterol: 0mg",
      "Sodium: 220mg",
      "Total Carbohydrate: 24g",
      "Protein: 1g",
    ],
    image_url: "<https://example.com/capn-crunch.jpg>",
  },
  {
    _id: "14",
    name: "Rice Krispies",
    brand: "Kellogg's",
    ingredients: ["Rice", "Sugar", "Salt", "Malt Flavoring"],
    nutritional_table: [
      "Calories: 130",
      "Total Fat: 0g",
      "Cholesterol: 0mg",
      "Sodium: 190mg",
      "Total Carbohydrate: 29g",
      "Protein: 2g",
    ],
    image_url: "<https://example.com/rice-krispies.jpg>",
  },
  {
    _id: "15",
    name: "Honey Bunches of Oats",
    brand: "Post",
    ingredients: [
      "Corn",
      "Whole Grain Wheat",
      "Sugar",
      "Whole Grain Rolled Oats",
      "Brown Sugar",
    ],
    nutritional_table: [
      "Calories: 120",
      "Total Fat: 2g",
      "Cholesterol: 0mg",
      "Sodium: 125mg",
      "Total Carbohydrate: 25g",
      "Protein: 2g",
    ],
    image_url: "<https://example.com/honey-bunches-of-oats.jpg>",
  },
  {
    _id: "16",
    name: "Apple Jacks",
    brand: "Kellogg's",
    ingredients: ["Corn", "Sugar", "Flour", "Oat Fiber", "Cinnamon"],
    nutritional_table: [
      "Calories: 110",
      "Total Fat: 0g",
      "Cholesterol: 0mg",
      "Sodium: 125mg",
      "Total Carbohydrate: 26g",
      "Protein: 1g",
    ],
    image_url: "<https://example.com/apple-jacks.jpg>",
  },
  {
    _id: "17",
    name: "Frosted Rice Krispies",
    brand: "Kellogg's",
    ingredients: ["Rice", "Sugar", "Malt Flavoring", "Salt"],
    nutritional_table: [
      "Calories: 130",
      "Total Fat: 0g",
      "Cholesterol: 0mg",
      "Sodium: 190mg",
      "Total Carbohydrate: 29g",
      "Protein: 2g",
    ],
    image_url: "<https://example.com/frosted-rice-krispies.jpg>",
  },
  {
    _id: "18",
    name: "Corn Pops",
    brand: "Kellogg's",
    ingredients: [
      "Milled Corn",
      "Sugar",
      "Soluble Corn Fiber",
      "Salt",
      "Malt Flavoring",
    ],
    nutritional_table: [
      "Calories: 120",
      "Total Fat: 0g",
      "Cholesterol: 0mg",
      "Sodium: 105mg",
      "Total Carbohydrate: 29g",
      "Protein: 1g",
    ],
    image_url: "<https://example.com/corn-pops.jpg>",
  },
  {
    _id: "19",
    name: "Cocoa Krispies",
    brand: "Kellogg's",
    ingredients: ["Rice", "Sugar", "Cocoa", "Malt Flavoring", "Salt"],
    nutritional_table: [
      "Calories: 150",
      "Total Fat: 1.5g",
      "Cholesterol: 0mg",
      "Sodium: 180mg",
      "Total Carbohydrate: 33g",
      "Protein: 1g",
    ],
    image_url: "<https://example.com/cocoa-krispies.jpg>",
  },
  {
    _id: "20",
    name: "Raisin Nut Bran",
    brand: "General Mills",
    ingredients: [
      "Whole Grain Wheat",
      "Raisins",
      "Wheat Bran",
      "Almonds",
      "Sugar",
    ],
    nutritional_table: [
      "Calories: 200",
      "Total Fat: 5g",
      "Cholesterol: 0mg",
      "Sodium: 200mg",
      "Total Carbohydrate: 44g",
      "Protein: 6g",
    ],
    image_url: "<https://example.com/raisin-nut-bran.jpg>",
  },
  {
    _id: "21",
    name: "Granola",
    brand: "Nature Valley",
    ingredients: [
      "Whole Grain Oats",
      "Sugar",
      "Canola Oil",
      "Rice Flour",
      "Honey",
    ],
    nutritional_table: [
      "Calories: 240",
      "Total Fat: 7g",
      "Cholesterol: 0mg",
      "Sodium: 135mg",
      "Total Carbohydrate: 40g",
      "Protein: 4g",
    ],
    image_url: "<https://example.com/granola.jpg>",
  },
  {
    _id: "22",
    name: "Frosted Cheerios",
    brand: "General Mills",
    ingredients: [
      "Whole Grain Oats",
      "Sugar",
      "Corn Starch",
      "Salt",
      "Tripotassium Phosphate",
    ],
    nutritional_table: [
      "Calories: 110",
      "Total Fat: 2g",
      "Cholesterol: 0mg",
      "Sodium: 140mg",
      "Total Carbohydrate: 23g",
      "Protein: 2g",
    ],
    image_url: "<https://example.com/frosted-cheerios.jpg>",
  },
  {
    _id: "23",
    name: "Life",
    brand: "Quaker",
    ingredients: [
      "Whole Grain Oat Flour",
      "Sugar",
      "Corn Flour",
      "Whole Wheat Flour",
      "Rice Flour",
    ],
    nutritional_table: [
      "Calories: 120",
      "Total Fat: 1.5g",
      "Cholesterol: 0mg",
      "Sodium: 160mg",
      "Total Carbohydrate: 25g",
      "Protein: 3g",
    ],
    image_url: "<https://example.com/life.jpg>",
  },
  {
    _id: "24",
    name: "Froot Loops",
    brand: "Kellogg's",
    ingredients: ["Corn", "Wheat", "Sugar", "Oat Flour", "Salt"],
    nutritional_table: [
      "Calories: 110",
      "Total Fat: 1g",
      "Cholesterol: 0mg",
      "Sodium: 135mg",
      "Total Carbohydrate: 25g",
      "Protein: 1g",
    ],
    image_url: "<https://example.com/froot-loops.jpg>",
  },
];
